version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    restart: always
  server:
    build:
      context: ./server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - client
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
